FROM datajoint/djlab:py3.8-debian

USER anaconda:anaconda

RUN mkdir /main/element-lab \
          /main/element-animal \
          /main/element-session \
          /main/workflow-session

# Copy user's local fork of elements and workflow
COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
COPY --chown=anaconda:anaconda ./element-session /main/element-session
COPY --chown=anaconda:anaconda ./workflow-session /main/workflow-session

# Install packages
RUN pip install -e /main/element-lab
RUN pip install -e /main/element-animal
RUN pip install -e /main/element-session
RUN pip install -e /main/workflow-session
RUN pip install -r /main/workflow-session/requirements_test.txt

WORKDIR /main/workflow-session

ENTRYPOINT ["tail", "-f", "/dev/null"]
