FROM datajoint/djbase:py3.9-debian-fcd8909

USER anaconda:anaconda

COPY ./workflow-session/docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."
WORKDIR /main/workflow-session

# Option 1 - Install DataJoint's remote fork of the workflow and elements
# RUN git clone https://github.com/datajoint/workflow-session.git /main/

# Option 2 - Install user's remote fork of element and workflow
#            or an unreleased version of the element
# RUN pip install git+https://github.com/<user>/element-lab.git
# RUN pip install git+https://github.com/<user>/element-animal.git
# RUN pip install git+https://github.com/<user>/element-session.git
# RUN git clone https://github.com/<user>/workflow-session.git /main/

# Option 3 - Install user's local fork of element and workflow
RUN mkdir /main/element-lab
COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
RUN pip install -e /main/element-lab
RUN mkdir /main/element-animal
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
RUN pip install -e /main/element-animal
RUN mkdir /main/element-session
COPY --chown=anaconda:anaconda ./element-session /main/element-session
RUN pip install -e /main/element-session
COPY --chown=anaconda:anaconda ./workflow-session /main/workflow-session
# RUN rm -f /main/workflow-session/dj_local_conf.json

# Install the workflow
RUN pip install -e /main/workflow-session
RUN pip install -r /main/workflow-session/requirements_test.txt
